# Generated by Django 5.1.2 on 2024-10-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobsapp", "0002_alter_applicant_id_alter_favorite_id_alter_job_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
